---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../components/apps/nginx
patches:
  - path: helm-release.yaml
    target:
      kind: HelmRelease
      name: nginx

  - target:
      kind: HelmRelease
      group: helm.toolkit.fluxcd.io
      version: v2
      name: nginx
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-demo
      - op: replace
        path: /spec/releaseName
        value: nginx-demo
      - op: add
        path: /spec/values/fullnameOverride
        value: nginx-demo