---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: only-default-to-psql-0
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/minikube/custom-resources/flux-demo/np
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system