---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 5m
  releaseName: postgresql
  targetNamespace: <NAMESPACE>
  chart:
    spec:
      chart: postgresql
      version: "15.2.0" # postgresql version is 15.2.0 by default
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
