
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ip-cm
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/minikube/custom-resources/flux-demo/configmaps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system